In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [16]:
import time

a = np.random.rand(1000000);
b = np.random.rand(1000000);

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print('Vectorized time: ', str(1000 * (toc - tic)) + ' ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()    
print(c)
print('Non-vectorized time: ', str(1000 * (toc - tic)) + ' ms')


249846.09508617807
Vectorized time:  0.9021759033203125 ms
249846.09508618238
Non-vectorized time:  591.6459560394287 ms


In [29]:
n = 5
u = np.zeros((n, 1))
for i in range(5):
    print(i)

0
1
2
3
4


In [68]:

a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
c = np.random.randn(3, 4)
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [70]:
print(c)

[[ 0.1100626   2.16149978 -0.75485773 -0.12943966]
 [-0.25371654  0.77404722  0.20313532 -2.10633646]
 [-0.11786523  0.46242546 -0.20255776 -1.90477455]]


In [87]:
import numpy as np
print(np.add(a, b.T))

[[ 0.1100626   2.16149978 -0.75485773 -0.12943966]
 [-0.25371654  0.77404722  0.20313532 -2.10633646]
 [-0.11786523  0.46242546 -0.20255776 -1.90477455]]


In [92]:
a = np.array([[1, 2, 3], [1, 2, 3]])
print(a.shape)

(2, 3)


In [100]:
np.zeros((1, 5))

array([], shape=(0, 5), dtype=float64)

In [101]:
w = np.array([[0.1124579],[0.23106775]])

In [104]:
w.reshape(1, 2).shape

(1, 2)